name: Sync Fork from Upstream

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 03:00 UTC
  workflow_dispatch:      # Manual trigger via GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository (your fork)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/gethomepage/homepage.git
          git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git checkout main
          git merge --no-edit upstream/main || true

      - name: Push changes to fork
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
